const MINT_PRICE = 0.06; // In eth
const MAX_TOKEN_SUPPLY = 887;
const CONTRACT_ADDRESS = "0x975eb08A1B1FF1782bb889dFa1D043657d1fCA23";
const NFT_NAME = "Unruggables";
const CHAIN_NAME = "Rinkeby Testnet";
const CHAIN_ID = 4;

export default { MINT_PRICE, MAX_TOKEN_SUPPLY, CONTRACT_ADDRESS, NFT_NAME, CHAIN_NAME, CHAIN_ID };
